//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[Data] Site Settings</summary>
	[PublishedContentModel("dataSiteSettings")]
	public partial class DataSiteSettings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataSiteSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataSiteSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataSiteSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cookie Agree Button Text
		///</summary>
		[ImplementPropertyType("cookieAgreeButtonText")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> CookieAgreeButtonText
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("cookieAgreeButtonText"); }
		}

		///<summary>
		/// Cookie Disagree Button Text
		///</summary>
		[ImplementPropertyType("cookieDisagreeButtonText")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> CookieDisagreeButtonText
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("cookieDisagreeButtonText"); }
		}

		///<summary>
		/// Cookie Read Mode Button Text
		///</summary>
		[ImplementPropertyType("cookieReadModeButtonText")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> CookieReadModeButtonText
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("cookieReadModeButtonText"); }
		}

		///<summary>
		/// Cookie Read More Link
		///</summary>
		[ImplementPropertyType("cookieReadMoreLink")]
		public Umbraco.Web.Models.RelatedLinks CookieReadMoreLink
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("cookieReadMoreLink"); }
		}

		///<summary>
		/// Cookie Short Copy
		///</summary>
		[ImplementPropertyType("cookieShortCopy")]
		public Our.Umbraco.Vorto.Models.VortoValue<IHtmlString> CookieShortCopy
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IHtmlString>>("cookieShortCopy"); }
		}

		///<summary>
		/// Links
		///</summary>
		[ImplementPropertyType("links")]
		public Umbraco.Web.Models.RelatedLinks Links
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("links"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("logo"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> Phone
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("phone"); }
		}

		///<summary>
		/// Site Search Page
		///</summary>
		[ImplementPropertyType("siteSearchPage")]
		public Umbraco.Web.Models.RelatedLinks SiteSearchPage
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("siteSearchPage"); }
		}

		///<summary>
		/// Social Media
		///</summary>
		[ImplementPropertyType("socialMedia")]
		public Umbraco.Web.Models.RelatedLinks SocialMedia
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("socialMedia"); }
		}
	}
}
