//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[Page] Post</summary>
	[PublishedContentModel("pagePost")]
	public partial class PagePost : PublishedContentModel, IGeneralNavigation, IGeneralPageTags, IGeneralPresentation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pagePost";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PagePost(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PagePost, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("body")]
		public Our.Umbraco.Vorto.Models.VortoValue<IHtmlString> Body
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IHtmlString>>("body"); }
		}

		///<summary>
		/// Body Sections Main Grid
		///</summary>
		[ImplementPropertyType("bodySectionsMainGrid")]
		public Newtonsoft.Json.Linq.JToken BodySectionsMainGrid
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("bodySectionsMainGrid"); }
		}

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("heading")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> Heading
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("heading"); }
		}

		///<summary>
		/// Main Image
		///</summary>
		[ImplementPropertyType("mainImage")]
		public IPublishedContent MainImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("mainImage"); }
		}

		///<summary>
		/// Sidebar - Category Specific Details
		///</summary>
		[ImplementPropertyType("sidebarCategorySpecificDetails")]
		public Newtonsoft.Json.Linq.JToken SidebarCategorySpecificDetails
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("sidebarCategorySpecificDetails"); }
		}

		///<summary>
		/// Subheading
		///</summary>
		[ImplementPropertyType("subheading")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> Subheading
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("subheading"); }
		}

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> NavigationTitle
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralNavigation.GetNavigationTitle(this); }
		}

		///<summary>
		/// Show in Breadcrumbs
		///</summary>
		[ImplementPropertyType("showInBreadcrumbs")]
		public bool ShowInBreadcrumbs
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralNavigation.GetShowInBreadcrumbs(this); }
		}

		///<summary>
		/// Show in navigation
		///</summary>
		[ImplementPropertyType("showInNavigation")]
		public bool ShowInNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralNavigation.GetShowInNavigation(this); }
		}

		///<summary>
		/// Page Tags
		///</summary>
		[ImplementPropertyType("pageTags")]
		public IEnumerable<IPublishedContent> PageTags
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralPageTags.GetPageTags(this); }
		}

		///<summary>
		/// Presentation Body
		///</summary>
		[ImplementPropertyType("presentationBody")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PresentationBody
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralPresentation.GetPresentationBody(this); }
		}

		///<summary>
		/// Presentation Image
		///</summary>
		[ImplementPropertyType("presentationImage")]
		public IPublishedContent PresentationImage
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralPresentation.GetPresentationImage(this); }
		}

		///<summary>
		/// Presentation Title
		///</summary>
		[ImplementPropertyType("presentationTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PresentationTitle
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralPresentation.GetPresentationTitle(this); }
		}

		///<summary>
		/// Related Pages
		///</summary>
		[ImplementPropertyType("relatedPages")]
		public Umbraco.Web.Models.RelatedLinks RelatedPages
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralPresentation.GetRelatedPages(this); }
		}
	}
}
