//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[PCD] Planinski Vrhovi</summary>
	[PublishedContentModel("pCDPlaninskiVrhovi")]
	public partial class PCdplaninskiVrhovi : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pCDPlaninskiVrhovi";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PCdplaninskiVrhovi(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PCdplaninskiVrhovi, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Drzava
		///</summary>
		[ImplementPropertyType("drzava")]
		public IEnumerable<IPublishedContent> Drzava
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("drzava"); }
		}

		///<summary>
		/// Nadmorska Visina
		///</summary>
		[ImplementPropertyType("nadmorskaVisina")]
		public int NadmorskaVisina
		{
			get { return this.GetPropertyValue<int>("nadmorskaVisina"); }
		}

		///<summary>
		/// Planinski Venac
		///</summary>
		[ImplementPropertyType("planinskiVenac")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PlaninskiVenac
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("planinskiVenac"); }
		}

		///<summary>
		/// Prvi Uspon - Alpinisti: Imena Alpinista prvog uspona
		///</summary>
		[ImplementPropertyType("prviUsponAlpinisti")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> PrviUsponAlpinisti
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("prviUsponAlpinisti"); }
		}

		///<summary>
		/// Prvi Uspon - Datum: Datum prvog uspona
		///</summary>
		[ImplementPropertyType("prviUsponDatum")]
		public DateTime PrviUsponDatum
		{
			get { return this.GetPropertyValue<DateTime>("prviUsponDatum"); }
		}
	}
}
